export enum HikeArea {
  SouthCascades = 'South Cascades',
  Rainier = `Rainier Nat'l Park`,
  SnoqualmiePass = 'Snoqualmie Pass',
  Olympics = 'Olympics',
  Teanaways = 'Teanaways',
  AlpineLakes = 'Alpine Lakes',
  Highway2 = 'Hwy 2',
  MountainLoopHighway = 'Mtn Loop Hwy',
  Glacier = 'Glacier Peak Wilderness',
  NorthCascades = 'N Cascades',
  Baker = 'Mt Baker Wilderness',
  Canada = 'Canada',
  Other = 'Other',
}
